react-component/tree-select

README.md, examples/basic.js, src/Select.jsx, src/SelectTrigger.jsx
Current rc-tree-select has a hard coded offset for the dropdown menu. This PR adds option to override it.
=> add option for dropdownPopupAlign

src/Select.jsx, src/SelectTrigger.jsx
Seeing the following all over logs in dev:
```
require('rc-util') is deprecated, please require('rc-util/lib/xx')
`rcUtil classSet` is deprecated, use `classNames()` by `require('classnames')` instead
`rcUtil joinClasses()` is deprecated, use `classNames()` by `require('classnames')` instead
`rcUtil PureRenderMixin` is deprecated, use `react-addons-pure-render-mixin` by `require('react-addons-pure-render-mixin')` instead
```
=> Fix warnings from deprecated imports in rc-util

src/Select.jsx, tests/Select.spec.js
在  treeData 变化后没有去更新 _treeNodesStates 导致 https://github.com/ant-design/ant-design/issues/4084
=> Fix tree data update error

README.md, src/SelectTrigger.jsx, tests/Select.spec.js
close https://github.com/ant-design/ant-design/issues/4608
=> Add treeDefaultExpanedKeys

src/Select.jsx
The current loopTreeData does not pass all props of the data objects to the TreeNode. because of this, the treeNodeFilterProp of TreeSelect is limited to a small subset of the data.  With this fix, I can send this array to my tree data and filter on the itemName prop by setting the treeNodeLabelProp of TreeSelect.  Currently, TreeSelect default searching is happening against the value prop which causes issues if my value need to be the ID of a particular item.
```
const treeData = [
{
selectable: false,
label: <Tooltip title = "This item already has a template defined">
<span className="disabled-item-label">item Supercool</span>
</Tooltip>,
itemName: 'item Supercool',
value: '1',
key: '1',
id: '1',
pId: null,
},
{
label: <span className="item-label">Generic item</span>,
itemName: 'Generic …
```
=> pass all props of tree item to TreeNode

src/Select.jsx
Bug fix.
Detailed steps to reproduce the bug:
1.  enable search, set treeCheckable true, set inputValue null
2. input some search words
3. check a tree node
4. remove it, fail
[Demo: check select](http://react-component.github.io/tree-select/examples/basic.html)
=> fix:remove checked node error when enable search

examples/disable.html, examples/disable.js, src/Select.jsx, tests/Select.checkable.spec.js, tests/Select.multiple.spec.js, tests/Select.spec.js, tests/__mocks__/rc-trigger.js
close https://github.com/ant-design/ant-design/issues/6731
=> Fix clear cache

examples/util.js, src/Select.jsx, src/util.js
Eliminate String.split() and compare position strings directly.
Gives huge performance boost when handling lots of nodes, e.g.
https://react-component.github.io/tree-select/examples/big-data.html
=> Optimize node ancestor checks

src/Select.jsx, tests/Select.multiple.spec.js
ref: https://github.com/ant-design/ant-design/issues/10274
Stop propagation when close button click. （`rc-select` also need this update）
=> click close do not trigger Trigger

examples/basic.js, src/Base/BasePopup.jsx, src/Select.jsx, tests/Select.SearchInput.spec.js, tests/__snapshots__/Select.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/13245
=> Not loadData when tree select is in filter

src/hooks/useTreeData.ts
@zombieJ  如果children是null的话。要报错。如图：
=> fix: dataNodes must be array

examples/form.js, package.json
https://github.com/ant-design/ant-design/issues/9792#issuecomment-560265177
=> fix duplicate rc-tree

src/OptionList.tsx, tests/Select.spec.js
when treeData is empty
close ant-design/ant-design#21627
=> fix treeRef.current.scrollTo throw error

.prettierrc, package.json, src/OptionList.tsx, tests/Select.SearchInput.spec.js
fix https://github.com/ant-design/ant-design/issues/22204
=> fix control treeExpandedKeys

package.json
详细见：#228
依赖和 antd 主干的依赖保持一致：https://github.com/ant-design/ant-design/blob/4.0.3/package.json
=> 📦 fix antd 4.0.x bundle size

src/hooks/useSelectValues.ts, tests/Select.spec.js
fix https://github.com/ant-design/ant-design/issues/22553
=> fix: TreeSelect dynamic label

.gitignore, src/OptionList.tsx, src/hooks/useKeyValueMapping.ts, src/hooks/useSelectValues.ts, src/utils/legacyUtil.tsx, src/utils/valueUtil.ts, tests/Select.props.spec.js, tests/Select.spec.js, tests/Select.tree.spec.js, tests/utils.spec.js
fix ant-design/ant-design#24347
=> 以value查找label时不排除禁用的节点Entity

package.json, src/OptionList.tsx, tests/Select.props.spec.js, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/24747
=> fix: Tabs popup can not trigger click at first time

examples/treeNodeLabelProp.tsx, package.json, src/TreeSelect.tsx, tests/Select.tree.spec.js
fix https://github.com/ant-design/ant-design/issues/23079
v4 错误的把 treeNodeLabelProp 作用到了 Tree 中，它应该只作用到 option values 里
虽然是个 bug 但是也是个 breaking change，要发 minor
=> fix: treeNodeLabelProp should only work on result value

package.json, tests/Select.checkable.spec.js, tests/Select.spec.js, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
ref https://github.com/ant-design/ant-design/pull/26462
=> chore: Bump tree

examples/basic.tsx, package.json, src/OptionList.tsx, src/TreeSelect.tsx, src/utils/valueUtil.ts, tests/Select.checkable.spec.js, tests/Select.spec.js, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
将 `scrollTo` 能力暴露出来
相关 issue：
https://github.com/ant-design/ant-design/issues/24240
相关 PR：
https://github.com/react-component/tree/pull/393
https://github.com/react-component/select/pull/565
=> feat: mount scrollTo on ref

src/OptionList.tsx, src/generate.tsx, tests/Select.checkable.spec.js
resolve https://github.com/ant-design/ant-design/issues/31658
=> fix: Disabled option should also show in checked

.eslintrc.js, examples/disable.tsx, src/generate.tsx, tests/Select.checkable.spec.js, tests/__mocks__/rc-motion/lib/CSSMotionList.js
resolve https://github.com/ant-design/ant-design/issues/32184
=> fix: Cascader conduction missing async value

src/hooks/useTreeData.ts, tests/Select.tree.spec.js
resolve https://github.com/ant-design/ant-design/issues/32806
=> fix: TreeSelect should not generate children when it's undefined

src/utils/strategyUtil.ts, tests/Select.spec.js
close https://github.com/ant-design/ant-design/issues/33493
=> fix: show selected parent whose children were all disabled

src/TreeSelect.tsx
Closes https://github.com/ant-design/ant-design/issues/34375
[SelectProps](https://github.com/react-component/select/blob/master/src/Select.tsx#L98) needs to accept ValueType as it's first generic.
Right now, the type needs to be cast as any in order to work first.
Repro that shows arguments are not inferred and can be cast incorrectly: https://codesandbox.io/s/antd-typescript-forked-srs8ob?file=/demo.tsx
=> Fix typescript types for onSelect

README.md, package.json, src/OptionList.tsx, src/TreeSelect.tsx, src/TreeSelectContext.ts, tests/Select.tree.treeExpandAction.spec.js, tests/setup.js
See https://github.com/ant-design/ant-design/pull/35137 for more details.
=> Feat: support 'treeExpandAction' prop for TreeSelect

src/utils/valueUtil.ts, tests/Select.SearchInput.spec.js, tests/__snapshots__/Select.spec.js.snap
修复ant design 中 TreeSlect组件在清空搜索框的值之后，会触发loadData的问题。
fix https://github.com/ant-design/ant-design/issues/38566
=> fix: TreeSlect will trigger loadData when clearing the search

src/hooks/useFilterTreeData.ts
map filter 改成 reduce，少遍历一次。然后这里是递归，就不止少遍历一次了。
=> perf: map filter -> reduce

src/OptionList.tsx, tests/Select.spec.tsx
修复ant design 中 TreeSlect 组件 下拉框打开时 active option 没有跟随 value 高亮。
fix [ant-design/issues#38566](https://github.com/ant-design/ant-design/issues/42663)
=> fix: TreeSelect keyboard navigation has inconsistent focusing

src/OptionList.tsx
给 displayName 添加 dev 环境，减少打包产物体积（可能吧）
=> chore: add NODE_ENV to OptionList.displayName

README.md, examples/basic.tsx, examples/filter.tsx, package.json, src/OptionList.tsx, src/TreeSelect.tsx, src/TreeSelectContext.ts, tests/Select.multiple.spec.js, tests/Select.props.spec.js, tests/Select.spec.tsx, tests/__snapshots__/Select.checkable.spec.tsx.snap, tests/__snapshots__/Select.spec.tsx.snap, tests/shared/focusTest.js
feat: Supports onPopupScroll props
增加 onPopupScroll  回调
#https://github.com/ant-design/ant-design/issues/48528
=> feat: Supports onPopupScroll props
