react-component/tree-select

examples/single.js
`optionLabelProp` should be `treeNodeLabelProp`
=> Fix wrong property name

src/Select.jsx
Pass a selectable prop to TreeNode which value comes from treeData with each item, give us a window to decide if a certain node is selectable
=> add selectable prop while loopTreeData

src/util.js
This is a quick fix for the issue #25
=> #25 checking on item.pos to prevent errors

examples/basic.js, examples/util.js, package.json
ref https://github.com/ant-design/ant-design-mobile/issues/959
=> feat: upgrade rc-util to 4.x

package.json, src/PropTypes.js, src/Select.jsx, src/SelectTrigger.jsx, src/TreeNode.jsx
https://github.com/ant-design/ant-design/issues/5678
=> fix react createClass and PropTypes warning

src/Select.jsx, tests/Select.checkable.spec.js
close ant-design/ant-design#7312
=> Fix check error: labs is undefined

src/Select.jsx, src/SelectTrigger.jsx, src/util.js, tests/Select.checkable.spec.js
#https://github.com/ant-design/ant-design/issues/8581
#https://github.com/ant-design/ant-design/issues/8734
#https://github.com/ant-design/ant-design/issues/8423
=> Props onSelect should be triggered when treeCheckable is true

src/PropTypes.js
=> fix spell in prop valid

.gitignore, package.json
add dist script for external usage.
=> npm add dist script

src/Select.jsx, src/SelectTrigger.jsx, src/util.js
* Add micro task for delay to do focus after `Trigger` first time render
* clean up props which never used
* `saveRef` add cache function
=> Fix auto focus not working at first render

src/util.js, tests/Select.multiple.spec.js
https://github.com/ant-design/ant-design/issues/8580
=> pass props by customize

src/SelectTrigger.jsx
ref: 
* issue: https://github.com/ant-design/ant-design/issues/9857
* select code: https://github.com/react-component/select/blob/master/src/SelectTrigger.jsx#L134
=> uniform action for treeSelect as select

src/Select.jsx
ref: https://github.com/ant-design/ant-design/issues/9905
=> re-align when value change

src/SelectTrigger.jsx
Reverts react-component/tree-select#107
Add back when https://github.com/react-component/trigger/pull/86 ready
=> Revert "uniform action for treeSelect as select"

examples/basic.js, package.json, src/Select.jsx, src/Selector/MultipleSelector/Selection.jsx, src/Selector/MultipleSelector/index.jsx, src/util.js, tests/Select.multiple.spec.js, tests/Select.props.spec.js, tests/Select.spec.js, tests/__snapshots__/Select.multiple.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/9117
=> Support `maxTagCount`

package.json, src/Select.jsx, src/util.js, tests/Select.spec.js, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.props.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
=> update deps of rc-tree@1.14.x

examples/controlled.html, examples/controlled.js, src/Base/BasePopup.jsx, src/Select.jsx, tests/Select.tree.spec.js
ref: https://github.com/ant-design/ant-design/issues/12145
=> TreeSelect support expanded keys

src/Select.jsx
[#13500](https://github.com/ant-design/ant-design/issues/13500)
=> Selector should update height after the animation of Popup

.travis.yml, examples/basic.js, examples/big-data-generator.js, examples/big-data.js, examples/controlled.js, examples/disable.js, examples/dynamic.js, examples/filter.js, examples/form.js, package.json, src/Select.jsx, src/Selector/MultipleSelector/index.jsx, src/Selector/SingleSelector.jsx, src/util.js, tests/Select.checkable.spec.js, tests/Select.multiple.spec.js, tests/Select.props.spec.js, tests/Select.spec.js, tests/Select.tree.spec.js, tests/__snapshots__/Select.tree.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/14597
=> support empty string

package.json, src/Base/BasePopup.jsx, src/Popup/SinglePopup.jsx, src/Select.jsx, src/util.js, tests/Select.spec.js, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.props.spec.js.snap, tests/util.spec.js
ref: https://github.com/ant-design/ant-design/issues/14897
=> Scroll value into view

src/Selector/MultipleSelector/index.jsx, tests/Select.multiple.spec.js, tests/__snapshots__/Select.multiple.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/15921
=> multiple mode support `showSerch=false`

now.json, package.json
ref: https://github.com/react-component/tree/pull/245
=> feat: update `rc-tree` deps

src/Select.jsx
fix https://github.com/ant-design/ant-design/issues/19523
=> fix filterTreeNodeFn initial

tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
=> chore: update snapshot

examples/basic.tsx, package.json, src/TreeSelect.tsx, src/utils/valueUtil.ts, tests/__snapshots__/Select.checkable.spec.js.snap, tests/__snapshots__/Select.multiple.spec.js.snap, tests/__snapshots__/Select.spec.js.snap
ref https://github.com/ant-design/ant-design/pull/28520
=> feat: maxTagCount support responsive

src/OptionList.tsx, tests/Select.spec.js
close https://github.com/ant-design/ant-design/issues/29798
=> fix: selectable should works on treeData

src/OptionList.tsx
Fix ant-design/ant-design#30211, should update valueKeys when treeData change
=> fix(OptionList): should update valueKeys when treeData change

package.json
=> Bump rc-util from 5.0.5 to 5.7.0

package.json, src/OptionList.tsx
ref https://github.com/ant-design/ant-design/issues/33744
=> fix: TreeSelect key board highlight

src/OptionList.tsx, tests/Select.spec.js
close https://github.com/ant-design/ant-design/issues/33874
=> fix: onSelect should not be triggered when key enter is pressed if nothing is active

src/utils/strategyUtil.ts, tests/Select.spec.js
close https://github.com/ant-design/ant-design/issues/34221﻿
=> fix: should not select parent if some children is disabled

README.md, docs/demo/width.md, examples/width.tsx, src/OptionList.tsx, src/TreeSelect.tsx, src/TreeSelectContext.ts, tests/Select.props.spec.js
close https://github.com/ant-design/ant-design/issues/34495
close https://github.com/ant-design/ant-design/issues/33495
=> fix: dropdownMatchSelectWidth={false} not working

src/OptionList.tsx, src/hooks/useFilterTreeData.ts, tests/Select.tree.spec.js
fix https://github.com/ant-design/ant-design/issues/36873
=> fix: filter should ignore isLeaf

.fatherrc.js, package.json, src/TreeSelect.tsx, tests/Select.checkable.spec.js
fix https://github.com/ant-design/ant-design/issues/38126
=> fix: Should keep label when value not in options but in labelInValue

.fatherrc.ts
=> build: correct alias config

README.md, examples/custom-icons.tsx, package.json, tests/Select.props.spec.js, tests/__snapshots__/Select.spec.tsx.snap
升级 rc-select，移除 showArrow 属性，将 inputIcon 重命名为 suffixIcon
=> chore: bump rc-select

package.json
- https://github.com/ant-design/ant-design/pull/46667
=> chore(deps): bump rc-select from 4.10.0 to 4.11.0

examples/debug.tsx, tests/Select.SearchInput.spec.js
close https://github.com/react-component/tree-select/security/code-scanning/1
close https://github.com/react-component/tree-select/security/code-scanning/2
close https://github.com/react-component/tree-select/security/code-scanning/3
close https://github.com/react-component/tree-select/security/code-scanning/4
close https://github.com/react-component/tree-select/security/code-scanning/5
=> fix: code scanning alerts

examples/fieldNames.tsx, src/TreeSelect.tsx, tests/Select.props.spec.js
ref: https://github.com/ant-design/ant-design/issues/49631
=> fix:  render correct label with `fieldNames`(#49631)
